"""035_create_chat_log

Revision ID: 68a06302cf70
Revises: 29559ee607af
Create Date: 2025-08-18 16:02:43.353110

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
# 移除 postgresql 方言导入，JSONB → JSON

# revision identifiers, used by Alembic.
revision = '68a06302cf70'
down_revision = '646e7ca28e0e'
branch_labels = None
depends_on = None


# 原PostgreSQL的数据迁移SQL使用了safe_jsonb_cast函数和::jsonb类型转换
# 现改为MySQL兼容的JSON函数: 使用CAST(... AS JSON)和JSON_EXTRACT替代
# MySQL中JSON_VALID检查JSON是否合法，JSON_EXTRACT替代->>操作符
# 注意：op.execute() 每次只能执行一条语句，多条语句需拆分为列表逐条执行
sql_statements = [
    """INSERT INTO chat_log(type, operate, pid, ai_modal_id, messages, start_time, finish_time, token_usage, reasoning_content)
SELECT '0',
       '0',
       id,
       ai_modal_id,
       CASE WHEN JSON_VALID(full_sql_message) THEN CAST(full_sql_message AS JSON) ELSE JSON_QUOTE(full_sql_message) END,
       create_time,
       finish_time,
       CASE WHEN JSON_VALID(token_sql) THEN CAST(token_sql AS JSON) ELSE JSON_QUOTE(token_sql) END,
       CASE WHEN JSON_VALID(sql_answer) THEN JSON_UNQUOTE(JSON_EXTRACT(CAST(sql_answer AS JSON), '$.reasoning_content')) ELSE NULL END
FROM chat_record
WHERE full_sql_message IS NOT NULL""",

    """INSERT INTO chat_log(type, operate, pid, ai_modal_id, messages, start_time, finish_time, token_usage, reasoning_content)
SELECT '0',
       '1',
       id,
       ai_modal_id,
       CASE WHEN JSON_VALID(full_chart_message) THEN CAST(full_chart_message AS JSON) ELSE JSON_QUOTE(full_chart_message) END,
       create_time,
       finish_time,
       CASE WHEN JSON_VALID(token_chart) THEN CAST(token_chart AS JSON) ELSE JSON_QUOTE(token_chart) END,
       CASE WHEN JSON_VALID(chart_answer) THEN JSON_UNQUOTE(JSON_EXTRACT(CAST(chart_answer AS JSON), '$.reasoning_content')) ELSE NULL END
FROM chat_record
WHERE full_chart_message IS NOT NULL""",

    """INSERT INTO chat_log(type, operate, pid, ai_modal_id, messages, start_time, finish_time, token_usage, reasoning_content)
SELECT '0',
       '2',
       id,
       ai_modal_id,
       CASE WHEN JSON_VALID(full_analysis_message) THEN CAST(full_analysis_message AS JSON) ELSE JSON_QUOTE(full_analysis_message) END,
       create_time,
       finish_time,
       CASE WHEN JSON_VALID(token_analysis) THEN CAST(token_analysis AS JSON) ELSE JSON_QUOTE(token_analysis) END,
       CASE WHEN JSON_VALID(analysis) THEN JSON_UNQUOTE(JSON_EXTRACT(CAST(analysis AS JSON), '$.reasoning_content')) ELSE NULL END
FROM chat_record
WHERE full_analysis_message IS NOT NULL""",

    """INSERT INTO chat_log(type, operate, pid, ai_modal_id, messages, start_time, finish_time, token_usage, reasoning_content)
SELECT '0',
       '3',
       id,
       ai_modal_id,
       CASE WHEN JSON_VALID(full_predict_message) THEN CAST(full_predict_message AS JSON) ELSE JSON_QUOTE(full_predict_message) END,
       create_time,
       finish_time,
       CASE WHEN JSON_VALID(token_predict) THEN CAST(token_predict AS JSON) ELSE JSON_QUOTE(token_predict) END,
       CASE WHEN JSON_VALID(predict) THEN JSON_UNQUOTE(JSON_EXTRACT(CAST(predict AS JSON), '$.reasoning_content')) ELSE NULL END
FROM chat_record
WHERE full_predict_message IS NOT NULL""",

    """INSERT INTO chat_log(type, operate, pid, ai_modal_id, messages, start_time, finish_time, token_usage, reasoning_content)
SELECT '0',
       '4',
       id,
       ai_modal_id,
       CASE WHEN JSON_VALID(full_recommended_question_message) THEN CAST(full_recommended_question_message AS JSON) ELSE JSON_QUOTE(full_recommended_question_message) END,
       create_time,
       finish_time,
       CASE WHEN JSON_VALID(token_recommended_question) THEN CAST(token_recommended_question AS JSON) ELSE JSON_QUOTE(token_recommended_question) END,
       CASE WHEN JSON_VALID(recommended_question_answer) THEN JSON_UNQUOTE(JSON_EXTRACT(CAST(recommended_question_answer AS JSON), '$.reasoning_content')) ELSE NULL END
FROM chat_record
WHERE full_recommended_question_message IS NOT NULL""",

    """INSERT INTO chat_log(type, operate, pid, ai_modal_id, messages, start_time, finish_time, token_usage, reasoning_content)
SELECT '0',
       '6',
       id,
       ai_modal_id,
       CASE WHEN JSON_VALID(full_select_datasource_message) THEN CAST(full_select_datasource_message AS JSON) ELSE JSON_QUOTE(full_select_datasource_message) END,
       create_time,
       finish_time,
       CASE WHEN JSON_VALID(token_select_datasource_question) THEN CAST(token_select_datasource_question AS JSON) ELSE JSON_QUOTE(token_select_datasource_question) END,
       CASE WHEN JSON_VALID(datasource_select_answer) THEN JSON_UNQUOTE(JSON_EXTRACT(CAST(datasource_select_answer AS JSON), '$.reasoning_content')) ELSE NULL END
FROM chat_record
WHERE full_select_datasource_message IS NOT NULL""",
]

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('type', sa.Enum('0', name='typeenum', native_enum=False, length=3), nullable=True),
    sa.Column('operate', sa.Enum('0', '1', '2', '3', '4', '5', '6', name='operationenum', native_enum=False, length=3), nullable=True),
    sa.Column('pid', sa.BigInteger(), nullable=True),
    sa.Column('ai_modal_id', sa.BigInteger(), nullable=True),
    sa.Column('base_modal', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('reasoning_content', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    for stmt in sql_statements:
        op.execute(stmt)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('chat_log')
    # ### end Alembic commands ###
