"""039_create_terminology

Revision ID: 25cbc85766fd
Revises: fc23c4f3e755
Create Date: 2025-08-25 11:38:32.990973

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision = '25cbc85766fd'
down_revision = 'fc23c4f3e755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 移除 CREATE EXTENSION vector (PostgreSQL pgvector扩展)，向量存储已迁移至 Milvus

    op.create_table('terminology',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('pid', sa.BigInteger(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('word', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    # 移除 embedding 列 (原 pgvector.VECTOR 类型)，向量数据存储在 Milvus 中
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('terminology')
    # ### end Alembic commands ###
