"""empty message

Revision ID: cd23f594ac05
Revises: c1b794a961ce
Create Date: 2025-11-06 14:12:40.384804

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd23f594ac05'
down_revision = 'c1b794a961ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_record', sa.Column('sql_prase', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_record', 'sql_prase')
    # ### end Alembic commands ###