"""072_chat_record

Revision ID: f898322341a5
Revises: a2e2ecfa5a9c
Create Date: 2026-09-14 15:54:47.921806

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f898322341a5'
down_revision = 'a2e2ecfa5a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_record', sa.Column('extracted_keywords', sa.Text(), nullable=True, comment='关键词'))
    op.add_column('chat_record', sa.Column('expanded_keywords', sa.Text(), nullable=True, comment='扩展后的关键词'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_record', 'extracted_keywords')
    op.drop_column('chat_record', 'expanded_keywords')
    # ### end Alembic commands ###
